import { sortBy } from "lodash";

const tags = [
	{ value: "javascript", label: "JavaScript"},
	{ value: "java", label: "Java"},
	{ value: "c#", label: "C#"},
	{ value: "php", label: "PHP"},
	{ value: "python", label: "Python"},
	{ value: "android", label: "Android"},
	{ value: "jquery", label: "jQuery"},
	{ value: "html", label: "HTML"},
	{ value: "c++", label: "C++"},
	{ value: "ios", label: "IOS"},
	{ value: "css", label: "CSS"},
	{ value: "mysql", label: "MYSQL"},
	{ value: "sql", label: "SQL"},
	{ value: "asp.net", label: "ASP.NET"},
	{ value: "c", label: "C"},
	{ value: "r", label: "R"},
	{ value: "ruby-on-rails", label: "Ruby On Rails"},
	{ value: "arrays", label: "Arrays"},
	{ value: "node.js", label: "Node.js"},
	{ value: "objective-c", label: "Objective C"},
	{ value: ".net", label: ".NET"},
	{ value: "json", label: "JSON"},
	{ value: "sql-server", label: "SQL Server"},
	{ value: "angularjs", label: "Angularjs"},
	{ value: "swift", label: "Swift"},
	{ value: "iphone", label: "iPhone"},
	{ value: "regex", label: "Regex"},
	{ value: "django", label: "Django"},
	{ value: "ruby", label: "Ruby"},
	{ value: "excel", label: "Excel"},
	{ value: "ajax", label: "Ajax"},
	{ value: "python-3.x", label: "Python 3.x"},
	{ value: "angular", label: "Angular"},
	{ value: "xml", label: "XML"},
	{ value: "asp.net-mvc", label: "ASP.NET MVC"},
	{ value: "linux", label: "Linux"},
	{ value: "reactjs", label: "Reactjs"},
	{ value: "database", label: "Database"},
	{ value: "spring", label: "Spring"},
	{ value: "wordpress", label: "Wordpress"},
	{ value: "vba", label: "VBA"},
	{ value: "wpf", label: "WPF"},
	{ value: "string", label: "String"},
	{ value: "xcode", label: "Xcode"},
	{ value: "windows", label: "Windows"},
	{ value: "laravel", label: "Laravel"},
	{ value: "vb.net", label: "VB.NET"},
	{ value: "pandas", label: "Pandas"},
	{ value: "mongodb", label: "MongoDB"},
	{ value: "html5", label: "HTML5"},
	{ value: "multithreading", label: "Multithreading"},
	{ value: "eclipse", label: "Eclipse"},
	{ value: "bash", label: "Bash"},
	{ value: "git", label: "Git"},
	{ value: "oracle", label: "Oracle"},
	{ value: "postgresql", label: "Postgresql"},
];

export default sortBy(tags, tag => tag.value);